---
# tasks file for ansible-role-configure-host

- name: Run package update
  import_tasks: run-package-update.yml
  tags:
    - base
    - dependencies

- name: Install base dependencies
  import_tasks: install-dependencies.yml
  tags:
    - base
    - dependencies

- name: Set hostname
  import_tasks: set-hostname.yml
  when:
    - set_hostname is defined and set_hostname
  tags:
    - base
    - hostname

- name: Update hosts file
  import_tasks: update-hosts-file.yml
  when:
    - update_hosts_file is defined and update_hosts_file
  tags:
    - base
    - hosts

- name: Configure local storage
  import_tasks: configure-storage.yml
  tags:
    - base
    - storage
