---

- name: "Set hostname to {{ inventory_hostname }}"
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"
  when:
    - hostvars[inventory_hostname].ansible_host is defined
    - hostvars[inventory_hostname].ansible_host != 'localhost'
