---

# src: http://derpturkey.com/setting-host-with-ansible-in-ubuntu/
- name: Update hostname in /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1    {{ inventory_hostname }}'
    state: present

- name: Debug variable groups['compute_nodes']
  debug:
    var: groups['compute_nodes']

# src: https://gist.github.com/rothgar/8793800
- name: "Build hosts file"
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: '.*{{ item }}$'

    line: "{{ hostvars[item]['ansible_' + public_iface]['ipv4']['address'] }} {{item}}"
    state: present
    backup: yes
  when: hostvars[item].ansible_default_ipv4.address is defined
  loop: "{{ groups['compute_nodes']|flatten(levels=1) }}"
